services:
  db:
    container_name: bdr_postgresql_16
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=agoodpassword
      - POSTGRES_DB=bdr
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
